name: demo-ci
on: [push]
jobs: 
   build-container-ci:
     runs-on: ubuntu-latest
     steps:
        - uses: nateprice18f/testing/.github/workflows/build-container-ci.yml
        - run: echo "Linting dockerfile, scan, building, deploy"
        - with:
            some-input: 'value'
   build-container-dep:
     runs-on: ubuntu-latest
     steps:
        - uses: nateprice18f/testing/.github/workflows/build-container-dep.yml
        - run: echo "Linting config, scan, building, deploy"
        - with:
            some-input: 'value'

